# Configuração geral do Core
Config:
  
  # configure aqui os fragmentos e suas chances (todos criados no itemcreator)
  active_fragments: false
  # o jogador devera estar apenas no survival para quebrar os blocos e receber os fragmentos ?
  only_survival_fragments: false
  message_fragments: "&aVoce recebeu<nl>&a{fragmento}"
  # nome:chance
  blocks_fragments:
  - 21>0
  - 73>0
  - 74>0
  - 56>0
  - 129>0
  - 14>0
  - 15>0
  - 16>0
  fragments:
  - 'frag_ultrararo:0.001'
  - 'frag_comum:0.05'
  
  # coloque aqui o canal aonde os eventos serão anunciados (deixe "" caso nao queira usar!)
  channel_events: "1100867602227675328"
  
  # quando faltar este tempo para iniciar automaticamente será avisado no canal de eventos.
  time_warn_events: 10
  
  # configure o titulo dos warns
  warn_title: "{tag} Evento {evento}"
  
  # warn dos eventos
  # para desativar deixe em branco []
  warn_text:
  - ' '
  - '{tag} O Evento {evento} vai ser iniciado em {tempo}'
  - 'preparem-se e não percam esta oportunidade!'
  - ' '
  
  # warn de iniciar evento
  # para desativar deixe em branco []
  warn_start:
  - ' '
  - '{tag} O Evento {evento} foi iniciado!.'
  - ' '
  
  # habilitar os eventos e seus comandos?
  enable_events: false
  
  # comando para quem tem a permissao: hawkcore.commands.events
  events_command:
  - ' '
  - '{tag} &aComandos Disponíveis'
  - '&e/Eventos [Reload] &7- Recarregar configuração de todos os eventos.'
  - '&e/Eventos [List] &7- Listar o nome de todos os eventos que existem.'
  - ' '
  
  # configure aqui o menu dos eventos
  MenuEvents:
    title: "&8Eventos HawkCore"
    row: 3
    slots: [12,13,14,15,16]
    Icons:
      iconNext:
        ID: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjcxNmNhMzk1MTFhOTY3MjBjMzM3OWU3NzE5NjNiZWZlMjI0YjYwZWNjZWQ5ZTY5MzQ5NTk3NWVkYTgxZGU3MiJ9fX0=
        name: "&cPróximo"
        slot: 24
      iconBack:
        ID: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOThiNWU5ZDVhZmFjMTgzZjFmNTcwYzFiNmVmNTE1NmMxMjFjMWVmYmQ4NTUyN2Q4ZDc5ZDBhZGVlYjY3MjQ4NSJ9fX0=
        name: "&cAnterior"
        slot: 22
    Glass:
    - '160>10:1,2,10,18,26,27'
  
  # mensagem de login ao entrar
  join:
    active: false
    message: "&7[&a●&7] &f{player}"
    
  # mensagem de quit ao sair
  quit:
    active: false
    message: "&7[&c●&7] &f{player}"
  
  # Configure aqui os comandos
  commandDesenchant:
    active: false
    # valor para poder desencantar o item.
    value: 50
  
  # PlaceHolders:
  # %hawkcore_thirst_percent% - %hawkcore_thirst_bar%
  # %hawkcore_heat_percent% - %hawkcore_heat_bar%
  # atviar sede e calor ?
  thirst: false
  heat: false
  # 20 ticks = 1s, tickrate em que a fome ou sede vai ser alterada a todo instante 
  tickRate: 1
  # Ativar actionbar na atualização de calor e sede ?
  actionBarActive: false
  actionBar: "&3Água %hawkcore_thirst_bar% &7/ &cTemperatura %hawkcore_heat_bar%"
  
  # Configure aqui o nome das regioes do worldguard que não vai funcionar a sede e calor.
  regionsDisables:
  - ''
  
  # Configure aqui as mensagens da Thirst and Heat
  MensagensThirstHeat:
    waterFull: "&cvocê não pode tomar água por agora!"
  
  # Config geral da sede
  thirstConfig:
    # Configure a barra de progresso da sede, corDefault,corBackground,Icones,Inicio,Final
    bar: "&8,&3,█████,&8[,&8]>&f%hawkcore_thirst_percent%"
    # mundo em que a sede vai funcionar
    worlds:
    - 'world'
    # Valor maximo da sede
    maxValue: 100
    # Valor inicial da sede
    valueStart: 100
    # Valor que vai ser adicionado a sede conforme o jogador anda
    increase: 0.06
    # Valor que vai diminuir caso o jogador esteja tomando agua ou qualquer outro motivo.
    decrease: 0.05
    # Item que o jogador pode consumir para aumentar a porcentagem de agua per/Item. (item criado pelo itemcreator)
    item: agua
    # porcentagem de agua que vai aumentar caso o jogador consuma o item.
    item_percent_increase: 25
    # Dano após ficar desidratado
    damage: 1.5
    
  # Config geral do calor
  heatConfig:
    # Configure a barra de progresso do calor, corDefault,corBackground,Icones,Inicio,Final
    bar: "&8,&c,█████,&8[,&8]>&f%hawkcore_heat_percent%"
    # mundo em que o calor vai funcionar
    worlds:
    - 'world'
    # Valor maximo do calor, aonde o jogador vai começar a pegar fogo.
    maxValue: 80
    # Valor maximo para começar a escurecer a vista do jogador
    blindnessValue: 60
    # Valor minimo do calor
    valueStart: 10
    # Valor que vai ser adicionado ao calor conforme o jogador anda
    increase: 0.05
    # Valor que vai diminuir caso o jogador esteja tomando agua ou qualquer outro motivo.
    decrease: 0.5
    # Item(s) que se o jogador usar pode diminuir sua temperatura. (item criado pelo itemcreator)
    # item:decreaseValue (valor por item) (caso o player esteja usando mais que um dos item(s) a temperatura pode cair mais rapido!)
    items:
    - 'bota:0.35'
    # dano após ficar super aquecido
    damage: 0.5
    

#=-=-=-=-=-=-=-=-=-
# Missões
#=-=-=-=-=-=-=-=-=-
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# IDS das missões
# 1 - Quebrar blocos
# 2 - Dropar Item
# 3 - Andar Distância
# 4 - Pegar um Item dropado
# 5 - Colocar blocos
# 6 - Matar uma entidade especifica
# 7 - Encantar um item aleatorio
# 8 - Craftar um item aleatorio.
# 9 - Encher a barra da fome.
# 10 - Escrever algo no chat.
# 11 - Quebrar um item qualquer.
# 12 - Quebrar um item especifico.
# 13 - Craftar um item especifico
# 14 - Encantar um item especifico.
# 15 - Pegar um item dropado especifico.
# 16 - Ganhar quantidade de experiência especifica.
# 17 - Pescar uma quantidade de vezes.
# 18 - Pescar um item especifico.
# 19 - Morrer quantidade de vezes.
# 20 - Atirar com o arco.
# 21 - Plantar um item aleatorio.
# 22 - Plantar um item especifico.
# 23 - Entregar um item especifico para a missão.
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# Configuração geral das missões
Missions:
  # Placeholders das missoes
  # %hawkcore_mission_{place}% veja os place abaixo:
  # missionName
  # missionDesc
  # missionProgress
  # missionMaxValue
  # missionValue
  # categoryName
  # categoryTotalMissions
  # categoryProgress
  # Tempo em minutos que as informações das missões do jogador serão salvas.
  activeMissions: false
  save_period: 5
  mission_complete: "&3✔ &9Você Completou a missão &b%hawkcore_missions_missionName%&9 da categoria %hawkcore_missions_categoryName%!"
  Menus:
    menuCategorys:
      name: "&8● Categorias - [{pagina}/{total}]"
      size: 5
      # slots das categorias
      slots: [11,12,13,14,15,16,17]
      concluido: "&a✔ Categoria Concluída"
      selecionada: 
      - ' '
      - '&6● Esta categoria esta selecionada'
      - ' '
      naoselecionada: 
      - ' '
      - '&c❓ Esta categoria esta pendente,'
      - '&cclique para selecionar.'
      - ' '
      Icons:
        iconNext:
          ID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjc2YjM5NmEzNDZmYmQ1ZGM5OGRmOWMwNjA5N2JiNTkxZmVmZDc2OGVkNWIzYmI5MGJiMzJhZjg1ZWI5MTQwNiJ9fX0="
          name: "&ePróxima Página"
          lore:
          - '&7clique para passar.'
          glow: false
          slot: 33
        iconBack:
          ID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTIxMjE3ZDdmZWU5ZmFmMmZiYzc0MWUwYWRiNWRlNmE4NGVhN2Q1NTM2Y2JjY2QxZGJjOGEzMjNmOTViOTkwZCJ9fX0="
          name: "&eVoltar Página"
          lore:
          - '&7clique para voltar.'
          glow: false
          slot: 31
        # Icone que vai aparecer caso não exista a categoria
        iconCategory:
          ID: 160>14
          name: "&c&m-/-"
          lore: []
          glow: false
      glass:
      - '160>2:1,9,37,45'
    menuMissions:
      name: "&8● Missões {nome} - [{pagina}/{total}]"
      size: 4
      # slots das missoes
      slots: [11,12,13,14,15,16,17]
      concluido: "&a✔ Missão Concluída"
      # ID do item quando a missão ainda não foi concluida.
      id: 340>0
      glow: false
      Icons:
        iconNext:
          ID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjc2YjM5NmEzNDZmYmQ1ZGM5OGRmOWMwNjA5N2JiNTkxZmVmZDc2OGVkNWIzYmI5MGJiMzJhZjg1ZWI5MTQwNiJ9fX0="
          name: "&ePróxima Página"
          lore:
          - '&7clique para passar.'
          glow: false
          slot: 25
        iconBack:
          ID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTIxMjE3ZDdmZWU5ZmFmMmZiYzc0MWUwYWRiNWRlNmE4NGVhN2Q1NTM2Y2JjY2QxZGJjOGEzMjNmOTViOTkwZCJ9fX0="
          name: "&eVoltar Página"
          lore:
          - '&7clique para voltar.'
          glow: false
          slot: 21
        # Icone que vai aparecer caso não exista a missao
        iconMission:
          ID: 160>14
          name: "&c&m-/-"
          lore: []
          glow: false
        iconCategorys:
          ID: 288>0
          name: "&eCategorias"
          lore:
          - '&7clique para ver as categorias.'
          slot: 23
          glow: true
      glass:
      - '160>2:1,2,3,4,5,36,35,34,33,32'
      
# Configure todas as mensagens do plugin aqui
Mensagens:
  commandDesenchant_sucess: "{tag} &aItem desencantado com sucesso!"
  commandDesenchant_itemErro: "{tag} &cSegure um item valido para poder desencantar."
  commandDesenchant_noMoney: "{tag} &cDinheiro insuficiente para desencantar, você precisa de {valor}!"
  permission: "{tag} &cVoce não tem permissão para executar isso!"