name: HawkCore
version: 4.1
author: lHawk_
description: Plugin para gerenciamento geral dos plugins Hawk.
depend: [PlaceholderAPI,nChat,WorldEdit,Vault,WorldGuard]
softdepend: [H_MasterTesouros,LuckyPerms]
load: STARTUP
awareness:
- !@UTF-8
main: me.hawkcore.Core
commands:
  desencantar:
    aliases: [desenchant]
    description: desencantar item(s)
  hawkcore:
    description: Comando geral do HawkCore.
  mission:
    aliases: [missao,missoes,missions]
    description: Comando geral do painel missões
  itemcreator:
    aliases: [ic]
    description: crie items customizados para dar aos jogadores.